export const PRODUCTS_REQUEST = 'PRODUCTS_REQUEST';
export const PRODUCTS_SUCCESS = 'PRODUCTS_SUCCESS';
export const PRODUCTS_FAILURE = 'PRODUCTS_FAILURE';

export const CREATE_FAVORITE = 'CREATE_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';

export const ADD_CART = 'ADD_CART';
export const DELETE_CART = 'DELETE_CART';

export const AUTH_CART_REQUEST = 'AUTH_CART_REQUEST';
export const AUTH_CART_SUCCESS = 'AUTH_CART_SUCCESS';
export const AUTH_CART_FAILURE = 'AUTH_CART_FAILURE';

export const PLUS_AMOUNT = 'PLUS_AMOUNT';
export const LESS_AMOUNT = 'LESS_AMOUNT';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';
